config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  get 'event_notices/new'
  get 'event_notices/sent'
  get 'events/new'
  root to: 'home#top'
  get 'home/about' => 'home#about', as: 'about'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books, only:[:create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only:[:create, :destroy]
    resources :book_comments, only:[:create, :destroy]
  end
  resources :users, only:[:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :groups, only:[:index, :new, :create, :show, :edit, :update, :destroy] do
    resource :group_users, only: [:create, :destroy]
    resources :event_notices, only:[:new, :create]
    get "event_notices" => "event_notices#sent"
  end
  resources :chats, only: [:show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  #1週間のいいね合計をFavoriteモデルから取ってくる。
  has_many :week_favorites, -> { where(created_at: ((Time.current.at_end_of_day - 6.day).at_beginning_of_day)..(Time.current.at_end_of_day)) }, class_name: 'Favorite'
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence:true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :owner, class_name: 'User'
  has_many :group_users
  has_many :users, through: :group_users, source: :user, dependent: :destroy
  has_many :events, dependent: :destroy

  has_one_attached :image

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-img.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit:[width, height]).processed
  end

  def is_owned_by?(user)
    owner.id == user.id
  end

  def includesUser?(user)
    group_users.exists?(user_id: user.id)
  end

  validates :name, uniqueness: true, presence: true
  validates :introduction, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  
   # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed
  
  has_many :favorites, dependent: :destroy
  has_many :favorited_books, through: :favorites, source: :book
  has_many :book_comments, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms

  has_one_attached :profile_image
  
  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-img.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit:[width, height]).processed
  end
  
  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @book_comment = current_user.book_comments.new(book_comment_params)
    @test = current_user.book_comments.new
    @book_comment.book_id = @book.id
    @book_comment.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    @book_comment = BookComment.find(params[:id]).destroy
    @book_comment= BookComment.new
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_comment.html.erb
<table>
  <% book.book_comments.each do |book_comment| %>
    <tr>
      <td>
        <%= image_tag book_comment.user.get_profile_image(50, 50) %><br>
        <%= book_comment.user.name %>
      </td>
      <td><%= book_comment.comment %></td>
      <% if book_comment.user == current_user %>
        <td><%= link_to 'Destroy', book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true,class: "btn btn-sm btn-danger" %></td>
      <% end %>
    </tr>
  <% end %>
</table>
<div>
  <%= form_with model: [book, book_comment], local: false do |f| %>
    <%= f.text_area :comment, style: "width:100%", rows: '5' %>
    <%= f.submit "送信" %>
  <% end %>
</div>

app/views/book_comments/_comments_count.html.erb
コメント件数: <%= @book.book_comments.count %>

app/views/book_comments/_list.html.erb
<table>
  <% book.book_comments.each do |book_comment| %>
    <tr>
      <td>
        <%= image_tag book_comment.user.get_profile_image(50, 50) %><br>
        <%= book_comment.user.name %>
      </td>
      <td><%= book_comment.comment %></td>
      <% if book_comment.user == current_user %>
        <td><%= link_to 'Destroy', book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true,class: "btn btn-sm btn-danger" %></td>
      <% end %>
    </tr>
  <% end %>
</table>
<div>
  <%= form_with model: [book, book_comment], remote: true do |f| %>
    <%= f.text_area :comment, style: "width:100%", rows: '5' %>
    <%= f.submit "送信" %>
  <% end %>
</div>

app/views/book_comments/create.js.erb
$(".comments_count").html("<%= j(render 'book_comments/comments_count', book: @book) %>");
$(".comments_area").html("<%= j(render 'book_comments/comment', book: @book, book_comment: @test) %>");
$("textarea").val('')

app/views/book_comments/destroy.js.erb
$(".comments_count").html("<%= j(render 'book_comments/comments_count', book: @book) %>");
$(".comments_area").html("<%= j(render 'book_comments/comment', book: @book, book_comment: @book_comment) %>");