config/routes.rb
Rails.application.routes.draw do
  get 'chats/show'
  get 'event_notices/new'
  get 'event_notices/sent'
  get 'events/new'
  root to: 'home#top'
  get 'home/about' => 'home#about', as: 'about'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :books, only:[:create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only:[:create, :destroy]
    resources :book_comments, only:[:create, :destroy]
  end
  resources :users, only:[:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
  	get 'followings' => 'relationships#followings', as: 'followings'
  	get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :groups, only:[:index, :new, :create, :show, :edit, :update, :destroy] do
    resource :group_users, only: [:create, :destroy]
    resources :event_notices, only:[:new, :create]
    get "event_notices" => "event_notices#sent"
  end
  resources :chats, only: [:show, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  #1週間のいいね合計をFavoriteモデルから取ってくる。
  has_many :week_favorites, -> { where(created_at: ((Time.current.at_end_of_day - 6.day).at_beginning_of_day)..(Time.current.at_end_of_day)) }, class_name: 'Favorite'
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence:true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :owner, class_name: 'User'
  has_many :group_users
  has_many :users, through: :group_users, source: :user, dependent: :destroy
  has_many :events, dependent: :destroy

  has_one_attached :image

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-img.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit:[width, height]).processed
  end

  def is_owned_by?(user)
    owner.id == user.id
  end

  def includesUser?(user)
    group_users.exists?(user_id: user.id)
  end

  validates :name, uniqueness: true, presence: true
  validates :introduction, presence: true
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  
   # 自分がフォローされる（被フォロー）側の関係性
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # 被フォロー関係を通じて参照→自分をフォローしている人
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  # 自分がフォローする（与フォロー）側の関係性
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 与フォロー関係を通じて参照→自分がフォローしている人
  has_many :followings, through: :relationships, source: :followed
  
  has_many :favorites, dependent: :destroy
  has_many :favorited_books, through: :favorites, source: :book
  has_many :book_comments, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms

  has_one_attached :profile_image
  
  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-img.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit:[width, height]).processed
  end
  
  def follow(user)
    relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    #1週間分のいいね合計順にsortするための記述
    to  = Time.current.at_end_of_day
    from  = (to - 6.day).at_beginning_of_day
    @books = Book.all.sort {|a,b|
    b.favorites.where(created_at: from...to).size <=>
    a.favorites.where(created_at: from...to).size
    }
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @books = Book.all
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id)
      flash[:notice] = "You have created book successfully."
    else
      render :index
    end
  end

  def show
    @new_book = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @books = Book.all
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id)
      flash[:notice] = "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @book = Book.new
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    @group.users << current_user
    if @group.save
     redirect_to groups_path
    else
      render :new
    end
  end

  #グループに参加する記述（group_userコントローラーを使っていないので不使用）
  #def join
    #@group = Group.find(params[:group_id])
    #@group.users << current_user
    #redirect_to  groups_path
  #end

  #グループから退出する記述（group_userコントローラーを使っていないので不使用）
  #def leave
    #@group = Group.find(params[:group_id])
    #@group.users.delete(current_user)
    #redirect_to groups_path
  #end

  def show
    @book = Book.new
    @group = Group.find(params[:id])
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.owner_id == current_user.id
      if @group.update(group_params)
        redirect_to group_path(@group)
      else
        render :edit
      end
    else
      redirect_to groups_path
    end
  end

  def destroy
    @group = Group.find(params[:id])
    if @group.owner_id == current_user.id
      @group.destroy
      redirect_to groups_path
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, :introduction, :image)
  end

  def ensure_correct_user
    @group = Group.find(params[:id])
    unless @group.owner_id ==current_user.id
      redirect_to groups_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Group</h1>
        <%= render 'layouts/errors', obj: @group %>
        <%= form_with model: @group, url: group_path(@group), method: :patch, local: true do |f| %>
          <div class="form-group">
            <label for="group_name">グループ名</label>
            <%= f.text_field :name, class: "form-control group_name" %>
          </div>
          <div class="form-group">
            <label for="group_introduction">紹介文</label>
            <%= f.text_area :introduction, class: "form-control group_introduction" %>
          </div>
          <div class="form-group">
            <label for="group_image">グループ画像</label><br>
            <%= f.file_field :image, class: "group_image" %>
          </div>
          <div class="form-group">
            <%= f.submit 'Update Group', class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/groups/index.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <%= render 'layouts/errors', obj: @book %>
    <div class="row">
      <%= render 'books/book', book: @book %>
      <div class="col-md-8 offset-md-1">
        <h2>Groups</h2>
        <div class="my-3">
          <%= link_to new_group_path, class: "btn btn-info rounded-circle p-1.5", style: "width:40px;height:40px;" do %>
            <i class="fa fa-plus"></i>
          <% end %>
        </div>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>グループ名</th>
              <th>紹介文</th>
              <th>メンバー数</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <% @groups.each do |group| %>
              <tr>
                <td>
                  <%= link_to group_path(group) do %>
                    <%= image_tag group.get_image(100, 100) %>
                  <% end %>
                </td>
                <td><%= link_to "#{group.name}", group_path(group), class: "group_#{group}" %></td>
                <td><%= group.introduction %></td>
                <td><%= group.group_users.count %></td>
                <% if group.owner_id == current_user.id %>
                  <td>
                    <%= link_to "Edit", edit_group_path(group), class: "btn btn-success" %>
                    <%= link_to "Destroy", group_path(group), method: :delete, class: "btn btn-danger ml-3" %>
                  </td>
                <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/groups/new.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Create Group</h1>
        <%= render 'layouts/errors', obj: @group %>
        <%= form_with(model: @group, local: true) do |f| %>
          <div class="form-group">
            <label for="group_name">グループ名</label>
            <%= f.text_field :name, class: "form-control group_name" %>
          </div>
          <div class="form-group">
            <label for="group_introduction">紹介文</label>
            <%= f.text_area :introduction, class: "form-control group_introduction" %>
          </div>
          <div class="form-group">
            <label for="group_image">グループ画像</label><br>
            <%= f.file_field :image, class: "group_image" %>
          </div>
          <div class="form-group">
            <%= f.submit 'Create Group', class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</main>

app/views/groups/show.html.erb
<main>
  <p id="notice"></p>
  <div class="container px-5 px-sm-0">
    <%= render 'layouts/errors', obj: @book %>
    <div class="row">
      <%= render 'books/book', book: @book %>
      <div class="col-md-8 offset-md-1">
        <h2>Group Detail</h2>
        <table class="table table-hover table-inverse">
          <thead>
            <tr>
              <th></th>
              <th>グループ名</th>
              <th>紹介文</th>
              <th>メンバー</th>
              <th></th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
                  <%= image_tag @group.get_image(100, 100) %>
              </td>
              <td><%= @group.name %></td>
              <td><%= @group.introduction %></td>
              <td>
                <% @group.users.each do |user| %>
                  <%= user.name %><br>
                <% end %>
              </td>
                <% if @group.is_owned_by?(current_user) %>
                  <td>
                    <%= link_to "Edit", edit_group_path(@group), class: "btn btn-success" %>
                    <%= link_to "Destroy", group_path(@group), method: :delete, class: "btn btn-danger ml-3" %>
                  </td>
                  <td><%= link_to "Notice an Event", new_group_event_notice_path(@group), class: "btn btn-info" %></td>
                <% elsif @group.includesUser?(current_user) %>
                  <%= link_to 'Leave This Group', group_group_users_path(@group), method: :delete, class: "btn btn-danger" %>
                <% else %>
                  <%= link_to 'Join This Group', group_group_users_path(@group), method: :post, class: "btn btn-success" %>
                <% end %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</main>